FORMAT: 1A

# public-example

# Group Upload

## Token [GET /upload/token]

+ Response 200 (application/json)

        "token panhezeng panhezeng"

## File [/upload/{file}]

+ Parameters
    + file

+ Model (application/json)

    + Headers

            Access-Control-Allow-Headers: Authorization,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Content-Length,ETag,Content-MD5
            Access-Control-Allow-Methods: PUT,GET,POST,DELETE,HEAD,OPTIONS,CONNECT,TRACE
            Access-Control-Allow-Origin: *
            Access-Control-Expose-Headers: ETag
            ETag: AQAAADl1GTvRN6B2wWyLspGGyHOSAEdj

    + Body

            {
                "Key": "panhezeng"
            }

### POST

+ Response 200

    [File][]

### PUT

+ Response 200

    [File][]
    
    
# Group ElSelectRemoteMultiple

## Options List [GET /el-select-remote-multiple/options{?limit,offset,search}]

+ Parameters
    + limit: 20 (number, optional) 
    + offset (number, optional)
    + search (string, optional)  
        
+ Response 200 (application/json)
    + Attributes (ElSelectRemoteMultiple Options)
    
## Option Create [POST /el-select-remote-multiple/option]

+ Request (application/json)

         { "name": "Option name 2"}
            
+ Response 200 (application/json)

         { "id": "2", "name": "Option name 2"}   
               
# Data Structures

## ElSelectRemoteMultiple Option (object)
+ id: 1
+ name: Option name 1

## ElSelectRemoteMultiple Options
+ count: 100 (number)
+ data (array[ElSelectRemoteMultiple Option])
