FORMAT: 1A

# public-example

## Group Upload

### Upload Token [/upload/token]

#### Upload Token [GET]

### Upload File [/upload/{file}]


#### Upload File POST [POST]


+ Response 200 (application/json)

    + Headers

            Etag: etagtest

    + Body

            {
                "Key": "Items/11933/11933A_1000x1000.jpg"
            }